services:

  maria:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: public
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    command: postgres -c 'max_connections=1000'
    ports:
      - 5432:5432

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
     #MYSQL_ROOT_USER: root
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307

  db-mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Root_root1
     #MSSQL_SA_USERNAME: sa
    ports:
      - 1433:1433

  db2:
    container_name: db2
    image: icr.io/db2_community/db2
    environment:
      LICENSE: accept
      DB2INSTANCE: root
      DB2INST1_PASSWORD: root
    ports:
      - 50000:50000

  oracle:
      shm_size: '8gb'
      container_name: oracle
      ports:
        - 9445:9445
      image: container-registry.oracle.com/database/standard
      environment:
        DB_SID: OraDoc
        DB_PASSWD: MyPasswd123
        DB_DOMAIN: my.domain.com
        DB_BUNDLE: basic
