name: Tests for db-messiah

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run e2e tests
        run: ./gradlew e2e

    services:
      maria:
        image: mariadb
        env:
          MARIADB_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      postgres:
        image: postgres
        env:
          POSTGRES_DB: public
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
        ports:
          - 5432:5432

      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_TCP_PORT: 3307
        ports:
          - 3307:3307

      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Root_root1
        ports:
          - 1433:1433

      db2:
        image: icr.io/db2_community/db2
        env:
          LICENSE: accept
          DB2INSTANCE: db2inst1
          DB2INST1_PASSWORD: root
          DBNAME: main
        ports:
          - 50000:50000
